# -*- coding: utf-8 -*-
"""App.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GAhFu12fsd9XhjmkFqOZvFXXzd4cyaF9
"""

from langchain_openai import ChatOpenAI
import os

llm = ChatOpenAI(
    model="llama-3.3-70b-versatile",
    groq_key = st.secrets["GROQ_API_KEY"],
    base_url="https://api.groq.com/openai/v1"
)


from langchain_core.prompts import PromptTemplate
from langchain_core.runnables import RunnablePassthrough
from langchain_core.output_parsers import StrOutputParser

prompt_template = """You are a medical report assistant. Use the context below to explain the medical report in simple language, highlight abnormal values, give a health summary, and suggest lifestyle tips.

Context: {context}

Question: {question}

Answer in simple, clear language a patient can understand:"""

prompt = PromptTemplate(template=prompt_template, input_variables=["context", "question"])

def format_docs(docs):
    return "\n\n".join(doc.page_content for doc in docs)

qa_chain = (
    {"context": retriever | format_docs, "question": RunnablePassthrough()}
    | prompt
    | llm
    | StrOutputParser()
)

print("Medical Report Assistant Ready! Type 'exit' to quit.\n")
while True:
    query = input("Ask about your report: ")
    if query.lower() == "exit":
        break
    response = qa_chain.invoke(query)
    print(f"\nAssistant: {response}\n")



# Commented out IPython magic to ensure Python compatibility.
# %%writefile medical_app.py
# # paste the entire medical_app.py code here



# Commented out IPython magic to ensure Python compatibility.
# %%writefile medical_app.py
# import streamlit as st
# import os
# import tempfile
# 
# st.set_page_config(page_title="MedReport AI", page_icon="🩺", layout="wide")
# st.title("🩺 Medical Report Intelligence Assistant")
# st.divider()
# 
# with st.sidebar:
#     st.header("⚙️ Setup")
#     groq_key = st.text_input("Groq API Key", type="password", placeholder="gsk_...")
#     uploaded_file = st.file_uploader("Upload Medical Report (PDF)", type=["pdf"])
#     process_btn = st.button("⚡ Analyse Report", use_container_width=True)
#     st.warning("⚠️ For informational purposes only. Always consult a doctor.")
# 
# if "messages" not in st.session_state:
#     st.session_state.messages = []
# if "qa_chain" not in st.session_state:
#     st.session_state.qa_chain = None
# 
# if process_btn:
#     if not groq_key or not uploaded_file:
#         st.sidebar.error("Please provide both API key and PDF.")
#     else:
#         with st.spinner("Reading report..."):
#             from langchain_community.document_loaders import PyPDFLoader
#             from langchain_text_splitters import RecursiveCharacterTextSplitter
#             from langchain_community.embeddings import HuggingFaceEmbeddings
#             from langchain_community.vectorstores import FAISS
#             from langchain_openai import ChatOpenAI
#             from langchain_core.prompts import PromptTemplate
#             from langchain_core.runnables import RunnablePassthrough
#             from langchain_core.output_parsers import StrOutputParser
# 
#             with tempfile.NamedTemporaryFile(delete=False, suffix=".pdf") as tmp:
#                 tmp.write(uploaded_file.read())
#                 tmp_path = tmp.name
# 
#             documents = PyPDFLoader(tmp_path).load()
#             docs = RecursiveCharacterTextSplitter(chunk_size=500, chunk_overlap=50).split_documents(documents)
#             embeddings = HuggingFaceEmbeddings(model_name="BAAI/bge-large-en-v1.5")
#             vectorstore = FAISS.from_documents(docs, embeddings)
#             retriever = vectorstore.as_retriever(search_kwargs={"k": 6})
# 
#             llm = ChatOpenAI(
#                 model="llama-3.3-70b-versatile",
#                 api_key=groq_key,
#                 base_url="https://api.groq.com/openai/v1"
#             )
# 
#             prompt = PromptTemplate(
#                 template="""You are a medical report assistant. Explain in simple language. Flag abnormal values with ⚠️.
# Context: {context}
# Question: {question}
# Answer:""",
#                 input_variables=["context", "question"]
#             )
# 
#             def fmt(docs): return "\n\n".join(d.page_content for d in docs)
# 
#             st.session_state.qa_chain = (
#                 {"context": retriever | fmt, "question": RunnablePassthrough()}
#                 | prompt | llm | StrOutputParser()
#             )
#             st.session_state.messages = []
#             os.unlink(tmp_path)
#         st.sidebar.success(f"✅ Done! {len(documents)} pages loaded.")
# 
# for msg in st.session_state.messages:
#     with st.chat_message(msg["role"]):
#         st.write(msg["content"])
# 
# if st.session_state.qa_chain:
#     user_input = st.chat_input("Ask about your report...")
#     if user_input:
#         st.session_state.messages.append({"role": "user", "content": user_input})
#         with st.chat_message("user"):
#             st.write(user_input)
#         with st.chat_message("assistant"):
#             with st.spinner("Thinking..."):
#                 answer = st.session_state.qa_chain.invoke(user_input)
#             st.write(answer)
#         st.session_state.messages.append({"role": "assistant", "content": answer})
# else:
#     st.info("👈 Upload your PDF and click Analyse Report to start.")

import subprocess, time
from pyngrok import ngrok

ngrok.kill()
subprocess.Popen(["streamlit", "run", "medical_app.py",
    "--server.port", "8501", "--server.headless", "true",
    "--server.enableCORS", "false", "--server.enableXsrfProtection", "false"])
time.sleep(5)
public_url = ngrok.connect(8501)
print(f"🚀 Live at: {public_url}")
